name: build and upload tagged release
on:
  push:
    tags:
      - "v*"

jobs:
  build_upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: build
        run: ./make.sh
      - name: version
        run: echo "version=$(./ytarchive -V)" >> $GITHUB_OUTPUT
        id: version
      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: ${{ steps.version.outputs.version }}
          files: |
            ytarchive_linux_amd64.zip
            ytarchive_windows_amd64.zip
            SHA2-256SUMS

